config/routes.rb
Rails.application.routes.draw do
  
  resources :projects do
  	resources :images
  end
  
  root 'projects#index'
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base

	validates :title, presence: true

	has_many :images

	accepts_nested_attributes_for :images, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	def new
		@image = Image.new
	end

	def index
		@project=Project.find(params[:project_id])
		@images = @project.images
	end

	def show
		@image = Image.find(params[:id])
	end

	def create
		@project = Project.find(params[:project])
    	@image = @project.images.build(image_params)
    	if @image.save
			redirect_to @image
		else
			render 'new'
		end
	end

	def edit
		@image = Image.find(params[:id])
	end

	def update
		@image = Image.find(params[:id])

		if @image.update(image_params)
			redirect_to @image
		else
			render 'edit'
		end
	end

	def destroy
		@image = Image.find(params[:id])
		@image.destroy

		redirect_to images_path
	end


	private
	def image_params
		params.require(:image).permit(:filename)
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def new
		@project = Project.new
	end

	def index
		@projects = Project.all
	end

	def show
		@project = Project.find(params[:id])
	end

	def create
		@project = Project.new(project_params)

		if @project.save
			redirect_to @project
		else
			render 'new'
		end
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])

		if @project.update_attributes(project_params)
			redirect_to @project
		else
			render 'edit'
		end
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy

		redirect_to projects_path
	end

	private
		def project_params
			params.require(:project).permit(:title, :text)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/images/index.html.erb
<link rel="stylesheet" type="text/css" href="application.css.scss">
<table class= "craft_table">

  <% @images.each do |image| %>
    <tr>
		<td><%= image_tag(image.filename, class: "craft_photo") %></td>
    </tr>
  <% end %>
  
</table>

app/views/images/show.html.erb
<p>
	<strong>Image filename:</strong>
	<%= @image.filename %>
</p>

app/views/layouts/_header.html.erb
<link rel="stylesheet" type="text/css" href="application.css.scss">
<div class="header_div">
	<div class="header_links_div">
	<%= link_to "HOME", projects_path, class: "header_text" %>
	<%= link_to 'NEW PROJECT', new_project_path, class: "header_text" %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craft Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/header" %>
	<%= yield %>
	<%= render "layouts/footer" %>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
  <div>
    <% @project.errors.full_messages.each do |error_message| %>
      <p><%= error_message %></p>
    <% end %>
  </div>
  <% end %>
  <p class="regular_text">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "title_field"%>
  </p>
 
  <p class="regular_text">
    <%= f.label :description %><br>
    <%= f.text_area :text, class: "text_box" %>
  </p>
  <p style="padding-bottom: 20px">
    <%= f.submit %>
  </p>
<% end %>

app/views/projects/edit.html.erb
<div class="craft_table">

	<h1 class="title_text">Edit Project</h1>
 
	<%= render 'form' %>
 
	<div style="padding-bottom: 10px">
		<%= link_to 'Delete Project', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: "red_link" %>
	</div>
</div>

app/views/projects/index.html.erb
<link rel="stylesheet" type="text/css" href="application.css.scss">
<table class= "craft_table">
	<tr>
		<td class="title_text"><strong>Projects</strong></td>
	</tr>
		<tr>
		<td class="regular_text">Click an image to see more of that project.</td>
	</tr>
  	<% @projects.each do |project| %>
    <tr>
    <% if project.images.first %>
        <td style="padding-bottom: 20px"><%= link_to image_tag(project.images.first.filename, class: "craft_photo"), project_path(project) %></td>
    <% else %>
    	<td><%= link_to project.title, project_path(project) %></td>
    <% end %>
  	</tr>
  <% end %>
  
</table>

app/views/projects/new.html.erb
<div class="craft_table">
	<h1 class="title_text">New Project</h1>

	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div class= "craft_table">
<table>
	<tr>
		<td class="title_text"><strong><%= @project.title %></strong></td>
	</tr>

	<tr>
		<td class="regular_text"><%= @project.text %></td>
	</tr>

	<% @project.images.each do |image| %>
    	<tr>
			<td><%= image_tag(image.filename, class: "craft_photo") %></td>
    	</tr>
	<% end %>

	<td class="bottom_link"><%= link_to 'Edit', edit_project_path(@project), class: "red_link" %></td>
</table>
</div>